-- Pre-baked distractors per difficulty for The Curator's Eye.
--
-- One artwork = 9 distractor scene strings total (3 per difficulty).
-- The correct answer is artwork.scene; the same correct answer is shown
-- in all difficulties. Only the 3 wrong options change.
--
-- Generated by scripts/backfill_distractors.mjs (one-time, ~$5-7 in API
-- calls). See scripts/distractors_update.sql for the resulting UPDATEs.
--
-- D1 ALTER does NOT support IF NOT EXISTS — run each statement once.
-- Re-running gives a harmless "duplicate column name" error.

ALTER TABLE artworks ADD COLUMN distractors_easy TEXT;
ALTER TABLE artworks ADD COLUMN distractors_medium TEXT;
ALTER TABLE artworks ADD COLUMN distractors_hard TEXT;
