#!/usr/bin/env node
// Drop religious-devotional items from the painting library.
//
// Identifies items whose title or scene matches devotional patterns
// (Annunciation, Crucifixion, Adoration, Madonna, Saint X, etc.) and:
//  1. Generates paintings_data/qc_drop_religious.sql for D1
//  2. Removes the dropped items from manifest_clean.json AND
//     manifest_historical.json (so a future re-upload doesn't bring them back)
//
// Usage: node scripts/drop_religious.mjs

import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const DATA_DIR  = path.resolve(__dirname, '..', 'paintings_data');

// Devotional patterns. We keep famous narrative biblical scenes that are
// historically interesting (Last Supper, David and Goliath) and historical
// figures with religious roles (Joan of Arc) by NOT matching them here.
const DEVOTIONAL = [
  /\bannunciation\b/i,
  /\badoration\s+of\s+(?:the\s+)?(?:magi|shepherds)\b/i,
  /\bvirgin\s+(?:and|with)\s+(?:the\s+)?child\b/i,
  /\bmadonna\b/i,
  /\bcrucifixion\b/i,
  /\bnativity\b/i,
  /\bholy\s+family\b/i,
  /\bpieta\b/i,
  /\bdormition\b/i,
  /\bcoronation\s+of\s+the\s+virgin\b/i,
  /\bvisitation\b/i,
  /\bpresentation\s+(?:of\s+jesus|in\s+the\s+temple|of\s+(?:the\s+)?virgin)\b/i,
  /\bflight\s+into\s+egypt\b/i,
  /\bentombment\b/i,
  /\blamentation\b/i,
  /\bdescent\s+from\s+the\s+cross\b/i,
  /\bdeposition\s+(?:from\s+(?:the\s+)?cross|of\s+christ|of\s+jesus)\b/i,
  /\bchrist\s+(?:bearing|carrying|teaching|blessing)\b/i,
  /\bchrist\s+(?:at|on|in|before)\b/i,
  /\bbaptism\s+of\s+christ\b/i,
  /\btransfiguration\b/i,
  /\bagony\s+in\s+the\s+garden\b/i,
  /\bgarden\s+of\s+gethsemane\b/i,
  /\bsaint\s+[a-z]+\s+(?:of|the|with)\b/i,        // "Saint Catherine of...", "Saint George the..."
  /\bst\.?\s+[a-z]+\s+(?:of|the|with)\b/i,
  /\bsacred\s+heart\b/i,
  /\baltarpiece\b/i,
  /\bmagdalen\s+(?:in|at|with)\b/i,
  /\bparable\s+of\b/i,
  /\bangels?\s+(?:sounding|trumpets|playing)\b/i,
  /\bcherubs?\b/i,
];

// EXCEPTIONS — keep these even if they match (famous secular-historical scenes
// that happen to use religious imagery or are real historical events)
const KEEP_ANYWAY = [
  /\bjoan\s+of\s+arc\b/i,                  // historical figure
  /\bcouncil\s+of\b/i,                     // Council of Nicaea, Trent etc.
  /\bcoronation\s+of\s+(?:napoleon|charlemagne|elizabeth)/i,  // royal coronations
  /\blast\s+supper\b/i,                    // famous narrative scene
  /\bdavid\s+and\s+goliath\b/i,
  /\bjudith\s+and\s+holofernes\b/i,
  /\bsamson\b/i,
  /\bmoses\s+(?:parting|crossing|receiving|leading)/i,
];

function isDevotional(item){
  const text = ((item.title || '') + ' | ' + (item.scene || '') + ' | ' + (item.scene_long || '')).toLowerCase();
  if (KEEP_ANYWAY.some(re => re.test(text))) return false;
  return DEVOTIONAL.some(re => re.test(text));
}

async function readJsonOrEmpty(file){
  try { return JSON.parse(await fs.readFile(path.join(DATA_DIR, file), 'utf8')); }
  catch(e) { console.log(`(skipped: ${file})`); return []; }
}

async function main(){
  const clean = await readJsonOrEmpty('manifest_clean.json');
  const hist  = await readJsonOrEmpty('manifest_historical.json');
  const wm    = await readJsonOrEmpty('manifest_wikimedia.json');
  const combined = await readJsonOrEmpty('manifest_combined.json');

  // Collect all devotional IDs across every manifest we have
  const dropIds = new Set();
  const samples = [];
  for (const m of [clean, hist, wm, combined]){
    for (const it of m){
      if (isDevotional(it)){
        dropIds.add(it.id);
        if (samples.length < 30) samples.push(`  ${it.id}  ${(it.title || it.scene || '').slice(0, 80)}`);
      }
    }
  }

  console.log(`\nIdentified ${dropIds.size} devotional items to drop.`);
  if (dropIds.size === 0) return;
  console.log('Sample drops:');
  samples.forEach(s => console.log(s));

  // Generate SQL
  const idArr = [...dropIds];
  const sql = `-- Drop religious-devotional items (${new Date().toISOString().slice(0,10)})\n` +
    `-- Generated by scripts/drop_religious.mjs\n` +
    `-- Run after this: re-upload via combine + upload_paintings (so the same\n` +
    `-- items don't get re-inserted).\n\n` +
    `DELETE FROM artworks WHERE id IN (\n  ` +
    idArr.map(id => `'${id.replace(/'/g, "''")}'`).join(',\n  ') +
    `\n);\n`;
  await fs.writeFile(path.join(DATA_DIR, 'qc_drop_religious.sql'), sql);
  console.log(`\nSQL written: paintings_data/qc_drop_religious.sql`);

  // Strip from local manifests so future re-uploads don't bring them back
  for (const [name, mfst] of [
    ['manifest_clean.json', clean],
    ['manifest_historical.json', hist],
    ['manifest_wikimedia.json', wm],
    ['manifest_combined.json', combined],
  ]){
    if (!mfst.length) continue;
    const filtered = mfst.filter(it => !dropIds.has(it.id));
    const removed = mfst.length - filtered.length;
    if (removed > 0){
      await fs.writeFile(path.join(DATA_DIR, name), JSON.stringify(filtered, null, 2));
      console.log(`  ${name}: removed ${removed}, kept ${filtered.length}`);
    }
  }

  console.log(`\nNext steps:`);
  console.log(`  1. Paste paintings_data/qc_drop_religious.sql into the D1 console.`);
  console.log(`  2. (Optional) re-run upload to regenerate scripts/artworks_seed.sql:`);
  console.log(`       MANIFEST_FILE=manifest_combined.json node scripts/upload_paintings.mjs`);
  console.log(`     This is only needed if you want manifest_combined.json refreshed for future steps.`);
}

main().catch(e => { console.error(e); process.exit(1); });
