#!/usr/bin/env node
// Bulk-upload painting library to R2 + generate D1 seed SQL
//
// Required env vars:
//   R2_ACCOUNT_ID     Cloudflare account ID (prefix of the R2 endpoint)
//   R2_ACCESS_KEY_ID  R2 API token access key
//   R2_SECRET_KEY     R2 API token secret
//   R2_BUCKET         bucket name (e.g. 'paintings')
//
// Usage:
//   npm install
//   node upload_paintings.mjs
//
// Input: paintings_data/manifest.json + images/ + thumbs/
// Output: scripts/artworks_seed.sql
// Side effect: uploads to R2 bucket

import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { S3Client, PutObjectCommand } from '@aws-sdk/client-s3';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const PROJECT_ROOT = path.resolve(__dirname, '..');
const DATA_DIR = path.join(PROJECT_ROOT, 'paintings_data');

// Allow overriding the manifest filename via env var (default: manifest.json)
const MANIFEST_FILE = process.env.MANIFEST_FILE || 'manifest.json';
// Skip uploading images that already exist in R2 (set SKIP_R2=1 to skip uploads entirely)
const SKIP_R2 = process.env.SKIP_R2 === '1';

const { R2_ACCOUNT_ID, R2_ACCESS_KEY_ID, R2_SECRET_KEY, R2_BUCKET } = process.env;
for (const [k, v] of Object.entries({ R2_ACCOUNT_ID, R2_ACCESS_KEY_ID, R2_SECRET_KEY, R2_BUCKET })){
  if (!v){ console.error(`Missing env var: ${k}`); process.exit(1); }
}

const s3 = new S3Client({
  region: 'auto',
  endpoint: `https://${R2_ACCOUNT_ID}.r2.cloudflarestorage.com`,
  credentials: {
    accessKeyId:     R2_ACCESS_KEY_ID,
    secretAccessKey: R2_SECRET_KEY,
  },
});

function sqlEscape(s){
  if (s == null) return 'NULL';
  return "'" + String(s).replace(/'/g, "''") + "'";
}

function sqlInt(n){
  return (n == null || n === '') ? 'NULL' : String(parseInt(n, 10));
}

async function uploadFile(localPath, r2Key, contentType){
  const body = await fs.readFile(localPath);
  await s3.send(new PutObjectCommand({
    Bucket: R2_BUCKET,
    Key: r2Key,
    Body: body,
    ContentType: contentType,
    CacheControl: 'public, max-age=31536000, immutable',
  }));
}

async function main(){
  const manifestPath = path.join(DATA_DIR, MANIFEST_FILE);
  const manifest = JSON.parse(await fs.readFile(manifestPath, 'utf8'));
  console.log(`Loaded ${manifest.length} artworks from ${MANIFEST_FILE}${SKIP_R2 ? ' (R2 uploads disabled)' : ''}`);

  let uploaded = 0, skipped = 0, errored = 0;
  const now = Math.floor(Date.now() / 1000);
  const inserts = [];

  for (let i = 0; i < manifest.length; i++){
    const art = manifest[i];
    const imgLocal = path.join(DATA_DIR, 'images', `${art.id}.jpg`);
    const thumbLocal = path.join(DATA_DIR, 'thumbs', `${art.id}.jpg`);

    try {
      // Check files exist
      await fs.access(imgLocal);
      await fs.access(thumbLocal);
    } catch(e){
      console.log(`  [${i+1}/${manifest.length}] ${art.id} SKIPPED: missing files`);
      skipped++;
      continue;
    }

    const imgKey = `images/${art.id}.jpg`;
    const thumbKey = `thumbs/${art.id}.jpg`;

    try {
      if (!SKIP_R2){
        await uploadFile(imgLocal, imgKey, 'image/jpeg');
        await uploadFile(thumbLocal, thumbKey, 'image/jpeg');
      }
      uploaded++;
      if ((i+1) % 10 === 0 || i === manifest.length - 1){
        console.log(`  [${i+1}/${manifest.length}] uploaded ${uploaded} OK, skipped ${skipped}, errored ${errored}`);
      }

      // Build SQL insert
      const distractorsJson = JSON.stringify(art.distractors || []);
      inserts.push(
        `INSERT OR REPLACE INTO artworks (id, source, source_id, image_key, thumb_key, title, artist, creation_year, depicted_era, scene, scene_long, distractors, medium, museum, culture, classification, difficulty, source_url, created_at) VALUES (` +
        [
          sqlEscape(art.id),
          sqlEscape(art.source),
          sqlEscape(String(art.source_id)),
          sqlEscape(imgKey),
          sqlEscape(thumbKey),
          sqlEscape(art.title),
          sqlEscape(art.artist),
          sqlInt(art.creation_year),
          sqlEscape(art.depicted_era),
          sqlEscape(art.scene),
          sqlEscape(art.scene_long),
          sqlEscape(distractorsJson),
          sqlEscape(art.medium),
          sqlEscape(art.museum),
          sqlEscape(art.culture),
          sqlEscape(art.classification),
          sqlInt(art.difficulty),
          sqlEscape(art.source_url),
          String(now),
        ].join(', ') + ');'
      );
    } catch(e){
      console.error(`  [${i+1}/${manifest.length}] ${art.id} ERRORED: ${e.message.slice(0, 160)}`);
      errored++;
    }
  }

  // Write SQL file
  const sqlPath = path.join(__dirname, 'artworks_seed.sql');
  const header = '-- Generated by upload_paintings.mjs\n-- Paste into Cloudflare D1 Console and execute\n\n';
  await fs.writeFile(sqlPath, header + inserts.join('\n') + '\n');

  console.log(`\nDONE.`);
  console.log(`Uploaded: ${uploaded}`);
  console.log(`Skipped:  ${skipped}`);
  console.log(`Errored:  ${errored}`);
  console.log(`SQL written to: ${sqlPath}`);
  console.log(`\nNext step: paste ${path.relative(PROJECT_ROOT, sqlPath)} into the Cloudflare D1 Console.`);
}

main().catch(e => { console.error(e); process.exit(1); });
